module Promise {
  fun reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  fun test : Promise(Never, Void) {
    sequence {
      greeting =
        Promise.reject("hello")

      void
    } catch String => a {
      void
    }
  }

  fun render : String {
    try {
      test()

      ""
    }
  }
}
--------------------------------------------------------------------------------
const B = new(class extends _M {
  c(e) {
    return
  }
})

class A extends _C {
  a() {
    return (async () => {
      let _ = null

      try {
        let b = await (async () => {
          try {
            return await B.c(`hello`)
          } catch (_error) {
            let d = _error
            _ = null
            throw new DoError()
          }
        })()

        _ = await null
      } catch (_error) {
        if (!(_error instanceof DoError)) {
          console.warn(`Unhandled error in sequence expression:`)
          console.warn(_error)
        }
      }

      return _
    })()
  }

  render() {
    return (() => {
      this.a()
      return ``
    })()
  }
}

A.displayName = "Main"
