module Result {
  fun error (input : a) : Result(a, b) {
    `new Err(input)`
  }
}

component Main {
  fun test : Promise(Never, String) {
    sequence {
      Result.error("")

      "test"
    } catch {
      "test"
    }
  }

  fun render : Html {
    try {
      test()

      <div/>
    }
  }
}
--------------------------------------------------------------------------------
const $Result = new(class {
  error(input) {
    return new Err(input)
  }
})

class $Main extends Component {
  test() {
    return (async () => {
      let _result = null;

      try {
        let _0 = $Result.error(``)

        if (_0 instanceof Err) {
          throw _0.value
        }

        _0.value

        _result = await `test`
      } catch (_error) {
        if (_error instanceof DoError) {} else {
          _result = `test`
        }
      }

      return _result
    })()
  }

  render() {
    return (() => {
      this.test.bind(this)()

      return _createElement("div", {})
    })()
  }
}

$Main.displayName = "Main"
